### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Bondok6** [eduardosancho/Leaderboard#3]
# HI @eduardosancho 🙋‍♂️

Good Job, your project is amazing. 🔥
Nice execution for sorting the scores.
Your code is clean.

**Comment by fherrerao** [comment]
# Hi @eduardosancho 💯 

- Your project looks really good 🦜 .
- Your code is clean.
- Correct use of modules.
- Use of JavaScript best practices.


![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)
